CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'USER',
    user_tim_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    vldAtivo BOOLEAN DEFAULT TRUE
);